### ISSUE TITLE
Default skin on Prod: Spacing / padding issues in Lessons

### ISSUE THREAD

**Issue by chrislorch** [DukeLearningInnovation/duke-sakai-skins#106]
Buttons are riding up over interface before/after content is added to Lessons.

<img width="1381" alt="alignmentissues2" src="https://user-images.githubusercontent.com/5098070/57630987-9e0bc500-756c-11e9-9dfe-e72168a91124.png">

<img width="1381" alt="spacing" src="https://user-images.githubusercontent.com/5098070/57631116-e0cd9d00-756c-11e9-8574-0afae36de8eb.png">

**Comment by profmikegreene** [comment]
#129 fixed these
