### ISSUE TITLE
Forum title / breadcrumbs appear above /below header buttons

### ISSUE THREAD

**Issue by chrislorch** [DukeLearningInnovation/duke-sakai-skins#146]
![thumbnail_screen_shot_2019-09-06_at_8 05 51_am~2](https://user-images.githubusercontent.com/5098070/64429430-03d40d80-d084-11e9-816f-696f3c624d96.png)

**Comment by profmikegreene** [comment]
dfViewThread still needs work, not centering in the breadcrumb area correctly.

**Comment by hrvalli** [comment]
I think this is cutting off the Forums header (next to the speech bubble icon). See screenshot. 
<img width="939" alt="forums_oddity" src="https://user-images.githubusercontent.com/19862293/65172924-d68c4580-da1b-11e9-8621-2e58c2dc4d66.png">
