### ISSUE TITLE
Favorites dropdown menu width is inconsistent with course name

### ISSUE THREAD

**Issue by wyu12** [DukeLearningInnovation/duke-sakai-skins#189]
![image](https://user-images.githubusercontent.com/20628667/71645769-321ccf00-2cab-11ea-9a45-bd33c3ebfd5b.png)
![image](https://user-images.githubusercontent.com/20628667/71645771-377a1980-2cab-11ea-9c61-2c8b2328d6f7.png)

**Comment by profmikegreene** [comment]
20.x favorites follow the material design pattern to hide the item you interacted with when the dropdown appears, which fixes this problem. 

This change was only in the 21 release and was reverted in 21. I can review the 21 release code and backport to 20 if we don't want to cover the favorites when you open it.
