### ISSUE TITLE
Disabled entry fields UI

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#190]
If a field is locked or not editable on a page, the UI should look different than the editable pages. Perhaps the background of field is grayed out. Including a Moodle example of a locked/disabled field as a comparison

Ex: Admin editing a course property field. 
**Nightly Example**
![NightlyExample](https://user-images.githubusercontent.com/1220785/71840135-b3e57180-308a-11ea-9c85-34738e19abcc.png)

**Duke Skin example**
![DukeExample](https://user-images.githubusercontent.com/1220785/71840181-c5c71480-308a-11ea-96a0-784a383a155c.png)

**Moodle comparison example**
![MoodleExample](https://user-images.githubusercontent.com/1220785/71840201-ce1f4f80-308a-11ea-8b66-647d5dc44743.png)

**Comment by profmikegreene** [comment]
This looks fixed to me
