### ISSUE TITLE
Forum direct link layering

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#192]
Doesn't seem to occur on 21.x Nightly as of Jan. 9, 2020 but occurs in current Duke 19.X prod instance.

If in a forum, select a topic and select a conversation thread. Try and select the **Link** option in upper right corner to get a direct link. If in a full desktop resolution, it will show **Link** and the link icon. They are not selectable though. If you rescale page to something smaller where the **Link** text is removed and only the icon remains, the button re-actives to get direct link. My assumption is there is something overlaying and thus the button isn't selectable. This also overlays the Help option that is next to Link option.
![Jan-09-2020 00-39-15](https://user-images.githubusercontent.com/1220785/72041134-b6a5b980-3278-11ea-8df4-c41747776706.gif)

**Comment by profmikegreene** [comment]
This was due to a customization that we're not maintaining moving forward.
