### ISSUE TITLE
Visual indicator for focused field missing

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#196]
Discovered while tabbing on a MC question page. 

To replicate:
1. Create quiz and select to add MC question
2. Use tab & shift +tab to move through page
3. Notice as you tab down, which field visual focus indicator says you are on. Easiest to see if you start at first answer choice field and then tab down. One tab should get you to correct answer radio button. Two tabs to Remove link. Three tabs to next answer field

Occurs on Duke 19.x; not on Nightly trunk

**Comment by msoupcoff** [comment]
Ex: https://warpwire.duke.edu/w/vXMDAA/

**Comment by profmikegreene** [comment]
fixed in 20.x upstream
