### ISSUE TITLE
Unpublished text labeled as primary button

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#232]
Can't tell if it's something in Nursing skin, having a lesson as the landing page or something else. Doesn't happen in all sites.

![Broken](https://user-images.githubusercontent.com/1220785/103141678-c0ad0c00-46c5-11eb-9cdc-a6bdf80ea4d5.png)

Ex: https://sakai.duke.edu/portal/site/NURSING.965.01.Sp21

**Comment by profmikegreene** [comment]
i can't reproduce when putting lessons as the first tool. I wonder if they have a custom lessons CSS that is messing with things.

**Comment by msoupcoff** [comment]
Does look like they uploaded a custom CSS file to that lesson. Closing as non-issue

https://sakai.duke.edu/portal/site/NURSING.965.01.Sp21
