### ISSUE TITLE
Resources | Action button color rollover

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#236]
When rolling over Action button, black text on dark blue background

![Resources](https://user-images.githubusercontent.com/1220785/104035109-bd268400-519f-11eb-956e-53fd58ca6ee8.gif)

**Comment by profmikegreene** [comment]
i'll need a url with this happening to debug. those styles are defined in the skin, seems like it might be a caching issue.

**Comment by msoupcoff** [comment]
Completely missed notification about needing URL. I don't remember the original site I took gif from though.

Further testing looks like it appears for when items & folders are hidden (ie either of the hidden options or the show option but with dates in past). Can see in this [test site](https://sakai.duke.edu/portal/site/fe80adcf-643e-46fa-9640-f612f1b049ff/tool/c3cddfdb-ca18-4743-940d-623a2b9b5360?panel=Main)

The 'Week 1' folder is set to 'Hide this folder but allow access to its contents'
The 'Week 2' folder is set to ' Hide this folder and its contents'
The 'jira.png' file is set to Show but with an 'Until' date in the past.

**Comment by profmikegreene** [comment]
thank you! i can fix with that info.
