### ISSUE TITLE
Date picker | Color contrast on buttons

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#243]
Looks to be different colors used in three scenarios: not selected/highlighted, hover & on-click. Specifically looking at the 'hour' & 'minute' buttons. This was while in a Quiz setting but assume same color issues would be present anywhere date picker is used in other tools.

The plus/minus symbol color against background of button fails most contrast tests. Is problem on nightly too for the whites/grays used. Duke blue is slightly better so we don't fail as many tests.

Note: Some of them were screenshot, put next to contrast tool & then screenshot again due to limitations on having something selected in two different tools at same time. So reported hex numbers may be slightly different than CSS numbers. Shouldn't be too far off though

Note 2: Issues on trunk during testing so used 21.x branch of nightly

### Duke Prod - Not selected/highlighted
![Picker-DukeProd-NotSelected](https://user-images.githubusercontent.com/1220785/109708278-3079c000-7b69-11eb-8f84-88483afea5b4.png)

### Duke Prod - Hover
![Picker-DukeProd-Hover](https://user-images.githubusercontent.com/1220785/109708299-37083780-7b69-11eb-8879-21496ae435f7.png)

### Duke Prod - Click
![Picker-DukeProd-Click](https://user-images.githubusercontent.com/1220785/109708333-425b6300-7b69-11eb-921b-da22bd2b0400.png)

### Nightly - Not selected/highlighted
![Picker-Nightly21x-NotSelected](https://user-images.githubusercontent.com/1220785/109708420-6454e580-7b69-11eb-9bd4-ff86235517b7.png)

### Nightly - Hover
![Picker-Nightly21x-Hover](https://user-images.githubusercontent.com/1220785/109708452-6dde4d80-7b69-11eb-9266-490f3e61d4e6.png)

### Nightly - Click
![Picker-Nightly21x-Click](https://user-images.githubusercontent.com/1220785/109708472-733b9800-7b69-11eb-8f32-4377cbe5de70.png)

**Comment by profmikegreene** [comment]
fixed upstream
