### ISSUE TITLE
Rubric button contrast

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#245]
https://jira.sakaiproject.org/browse/SAK-45165

Pretty much same as newly created jira except we also have some font color issues with cancel button

![RubricButtonContrastExample](https://user-images.githubusercontent.com/1220785/110854290-bd67fc00-8282-11eb-811d-eb33b61143c2.gif)

**Comment by profmikegreene** [comment]
can't get rubrics working on my localhost so this will probably take a couple cycles to fix.
