### ISSUE TITLE
RTE in Assignment > New Grader UI

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/duke-sakai-skins#279]
Reduced editor appears in New Grader **Feedback Text**, **Feedback comment** & **Private notes** popups

![NewGraderRTE](https://user-images.githubusercontent.com/1220785/130796532-f769e66a-47ba-4ea3-adc8-1316c8cce94c.gif)

**Comment by msoupcoff** [comment]
Looks to be different editor loaded as Nightly has reduced editor in New Grader UI as well

**Comment by profmikegreene** [comment]
This should be an upstream JIRA IMO. the new grader editors should respect the user's editor preference.
