### ISSUE TITLE
Style join page

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/duke-sakai-skins#29]
Hit https://sakai.duke.edu/portal/join/9abd97a0-0ce5-4079-b125-878f5b92c4af as a non-admin

**Comment by profmikegreene** [comment]
Recent patch styles it like this. Do you think this is good for Extend @JustinJohnsen ?
![sakai___joinable](https://user-images.githubusercontent.com/3632822/48733333-5be27600-ec10-11e8-8a33-caeae33572c2.png)

**Comment by JustinJohnsen** [comment]
Yes, that looks good. If it is possible to flip the Duke banner image with the 'Join This Site' bar, I would try that, because to me it seems like the Duke image might be a button that you click to join.
